{% set name = "magika" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/magika-{{ version }}.tar.gz
  sha256: 37eb6ae8020f6e68f231bc06052c0a0cbe8e6fa27492db345e8dc867dbceb067

build:
  entry_points:
    - magika-python-client = magika.cli.magika_client:main
    - magika = magika.cli.magika_rust_client_not_found_warning:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.1.7
    - onnxruntime >=1.17.0
    - numpy >=1.24
    - python-dotenv >=1.0.1

test:
  imports:
    - magika
  commands:
    - pip check
    - magika-python-client --help
    # Don't run this as it produces an intended error message
    # - magika --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/magika
  dev_url: https://github.com/google/magika/tree/main/python
  doc_url: https://github.com/google/magika
  summary: A tool to determine the content type of a file with deep-learning
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
